version: 1.0.{build}
image: Visual Studio 2019
environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
build_script:
  - dotnet pack -c Release -o out
artifacts:
  - path: out\*.*nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: jvTdXi6L2QU47Yo/w8DyOlBfbTiCDYAnMAGUUclLvvaD/qKlpYxBCqBbxap9XUrS
    on:
      branch: master
